### ISSUE TITLE
Intial load of addon newly installed - version 1.0.0

### ISSUE THREAD

**Issue by ceylina** [Sonaza/Candy#1]
Upon opening the interface options and candy settings for the first time, this happened:

This happens both on live and in beta

Candy\options-Options.lua:307: bad argument #1 to 'format' (string expected, got nil)
[C]: in function `format'
Candy\options-Options.lua:307: in function <Candy\options.lua:302>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1178: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1082: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1055>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1588: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1868: in function `Open'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:1896: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1894>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
Masque\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:20: in function <...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[C]: in function `Show'
FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil

Seems all that may be needed is a logic check to make sure data.icon is not nil?

**Comment by Sonaza** [comment]
Probably happens if some DataBroker module has opted to not include an icon? I haven't encountered this error myself but submitted a fix for it now.

Thank you for reporting the bug.
