### ISSUE TITLE
Suggestion - option to lock tooltip in combat

### ISSUE THREAD

**Issue by ceylina** [Sonaza/Candy#2]
Since some LDB addons tend to not respect combat locking and can throw errors in combat, I used other databroker's options to lock tooltips in combat.

Now I see you have the option to not show the ldb in combat which is great but would you be interested in adding an option to lock the tooltip in combat? I know I can add a custom LUA command to do that but as most people aren't familiar with LUA and it might be a nice feature to prevent errors of these other addons that are not coded the best. Locking per ldb would also be wonderful because that still leaves addons like skada open to clicking in combat.

Sometimes you still want to see the ldb's text display but you may accidentally mouse over it trying to click on that one squirrely trash mob and WHAM error!

BTW love the concept of this addon. Finally I can put objects where I want instead of just on a bar.

**Comment by Sonaza** [comment]
Shouldn't be big thing to add. Will do in the next version.

**Comment by ceylina** [comment]
<3!

**Comment by Sonaza** [comment]
Actually, I may have misunderstood what you mean. Tooltips are already hidden in combat so if it's not that then what? :D

**Comment by ceylina** [comment]
Show the broker display text but disable tooltips in combat. So let's say I have a broker addon that displays my location but has some tooltip display as well. If I hide the candy bar the broker addon is on, that location will hide in combat as well. If the bar is not hidden in combat but only the tooltip, it means if I accidentally mouse over that bar, it will not display a tooltip in combat.

Hopefully that makes better sense. If you already lock tooltips and interaction with the bars in combat ten this is a non issue but I have seen far too many addons raise errors in combat to know that locking in combat is a good thing.

**Comment by Sonaza** [comment]
Well it does check combat status in the OnEnter callback before displaying tooltips in [core.lua](https://github.com/Sonaza/Candy/blob/f21b420690aa9e4a03ba636628617d086c10bc14/core.lua#L644).

If that was what you were after then it was already there and I can close this ticket? :)

**Comment by ceylina** [comment]
Close away :D I just tested and it already does what I was thinking so yay!
