### ISSUE TITLE
Bug - disabling an addon and in turn it's candy bar that another bar is relative to hides the other bar

### ISSUE THREAD

**Issue by ceylina** [Sonaza/Candy#3]
This is a tough one because it might be something you can't account for but just a heads up.

I use buggrabber and bugsack to capture lua errors. On live I setup the candy bars how I like them and copied over the config to beta to see how it owrks. Everything shows fine except for bugsack. Now if I went into the config and removed the settings for bugsack then re-added it via "create a new candy bar" it shows just fine and no problems at all.

I really hope this is just a beta thing but if that happens to others when legion goes live, this is a heads up that bugsack is one of those that you can test against. 

Not even sure if it is anything you can test against.

Also, bug sack defaults  to "0" as the ldb text

**Comment by ceylina** [comment]
Just more observation and it could all revolve around the default text being the number 0 

In live I have the bar placed relative to another bar but on beta that addon is disabled and as such the bar that bugsack referenced is not enabled in candy.

Could it be that having a bar referenced to another bar then having said reference bar's addon disabled messes with placement?


Here are the configs for example:

Live:

			["BugSack"] = {
				["enabled"] = true,
				["justify"] = "RIGHT",
				["anchors"] = {
					{
						["relativeTo"] = "CandyBroker_PortalsFrame",
						["point"] = "TOPRIGHT",
						["relativePoint"] = "BOTTOMRIGHT",
					}, -- [1]
				},
			},

Beta:

			["BugSack"] = {
				["enabled"] = true,
				["justify"] = "RIGHT",
				["anchors"] = {
					{
						["y"] = 882.666687011719,
						["x"] = 2132.16479492188,
						["point"] = "RIGHT",
						["relativePoint"] = "BOTTOMLEFT",
					}, -- [1]
				},
			},

To further test, I re-enabled toyboxq (an addon that broker portals is relative to) broker_portals and yes, bugsack's candy bar showed up.

So, it seems that if you make a bar relative to another bar then disable that bar's addon, the relative to bar hides.

**Comment by Sonaza** [comment]
Okay, need to check if I can fix that :)

**Comment by Sonaza** [comment]
Attempted fix in version 1.0.2.

**Comment by ceylina** [comment]
Still happening. 

So here is a little example of what I mean.

I have 3 addons, let's call them A, B and C Now I creat new candy bars for the broker displays for A , B and C

Now if I take A and B and make them relative to each other like so

AB

and I then go into addons and disable the addon A, then B's bar dissapears because it is attached along with A which is the addon is no longer enabled

But If I take A,B, and C's bar and attach them all together so they are relative like so

ABC then disable the addon for B it looks like this: A

C is now no longer showing the bar for it because it was relative to B and B's addon was disabled.

We can go even one further. If the three addon's bars are all stuck together like so: ABC and I disable A then B and C's bars will vanish because A's addon is disabled.

**Comment by ceylina** [comment]
tested deleting the config and recreating the bars... no luck but wanted to rule out having to scrap the config between 1.0.1 and 1.0.2

**Comment by Sonaza** [comment]
I just thought about it and it isn't just matter of parent frame being missing though. The way the frames are restored when reloading interface will create all existing bars no matter what and shouldn't hide them either.

Problem is that if a parent frame is missing then the previously relative coordinates to parent are now relative to UIParent and the frame probably still is somewhere on the screen or a bit outside of it. One way to fix it would be saving absolute coordinates of the module just in case.

**Comment by ceylina** [comment]
Was going to suggest have an absolute coordinate as backup in case the bar it is attached to is disabled. Will test when you have something and if it works, I will let you know. Not having any bars "attach" to each other works for now and is how I have it running on live nad beta.

**Comment by Sonaza** [comment]
Should be fixed (properly) in [1.0.3](https://github.com/Sonaza/Candy/commit/2c2f139d47a15dacba1c9b6a7ceb59717afa951a).

**Comment by ceylina** [comment]
Works on my end so we good :D
