### ISSUE TITLE
addons that don't put a text tag in the ldb options section don't show text on the candy bar

### ISSUE THREAD

**Issue by ceylina** [Sonaza/Candy#4]
Wanted to put this as a new ticket so it can be a separate issue.

I am testing a new addon for legion called worldquest. It's an ldb addon but I noticed that they tag a label tag for the databroker object but not a text tag. This means that if the icon is not displayed on the candy bar, it is simply a blank bar. They have label set and when I edited the lua file and added text it shows up on candy's bar for this addon.

Any chance you can account for sloppy coding by others and add in a check for label in the databroker object if the text tag is missing?

Here is the snippet of their code to show what I mean

BWQ.WorldQuestsBroker = ldb:NewDataObject("WorldQuests", {
	type = "launcher",
	label = "World Quests",

When I add

text = "World Quests",

it shows on candy

**Comment by Sonaza** [comment]
Sure.

**Comment by Sonaza** [comment]
Fixed in version 1.0.2.
