### ISSUE TITLE
Thought: Add option to hide oder hall bar?

### ISSUE THREAD

**Issue by ceylina** [Sonaza/Candy#7]
That order hall bar is one of the worst things Blizzard has added. It's obtrusive and ugly as sin.

Any thought on adding a simple setting to either hide or fade out the order hall bar?

Some ideas:

https://mods.curse.com/addons/wow/hideorderhallbar

https://github.com/riphie/Riphie_OrderHall

No I am not asking to have this added because there are tons of addons and it is easy enough to build one to simply hide it but I think it would be a nice little addition and you could call the function "NukeFromOrbit" ;)

**Comment by Sonaza** [comment]
Not sure what bar you're speaking about exactly (I don't have beta so I haven't been able to test any class halls or related stuff).

In any case feature like this is out of scope for addon that's meant to be a DataBroker display only so I don't think I'll be adding it, at least in this addon.
