### ISSUE TITLE
Some bars removed upon reload/relog

### ISSUE THREAD

**Issue by Crelam** [Sonaza/Candy#8]
When adding a bar for a few particular addons, the bar will disappear upon reload/relog.  I don't know what commonalty these addons have, but these are the addons I have found that demonstrate this issue with Candy (I'm sure there are others out there):

ArkInventory (https://www.wowace.com/projects/ark-inventory)
Buffet (https://www.wowace.com/projects/buffet)
Rematch (https://wow.curseforge.com/projects/rematch)
ShuckIt (https://mods.curse.com/addons/wow/shunkit)

These four work with other LDB display addons and only disappear in Candy.  Thank you for your time and attention to detail.

**Comment by Sonaza** [comment]
Did it start happening after the recent update? It changed some of the internal frame naming that may be causing the error.

**Comment by Crelam** [comment]
That I cannot say.  I just recently tried your addon.  Is it safe to install the older version over this one or will it muck up the saved variables?

**Comment by Crelam** [comment]
Just installed v2.0.5 over the current version and had the same issue.

**Comment by Sonaza** [comment]
Fixed the bug in update version 2.0.7.

Error was related to addons that delay the creation of data broker module and my addon wasn't properly subscribed to the creation event.
